source 'https://github.com/CocoaPods/Specs.git'

target 'Deck', :exclusive => true do
  use_frameworks!
  pod "Deck", :path => "../"
end

target 'Tests', :exclusive => true do
  use_frameworks!
  pod "Deck", :path => "../"

  
end
